### ISSUE TITLE
How random board generator ensures no dead end conditions?

### ISSUE THREAD

**Issue by aik099** [shaos/rw1js#2]
As I understand (from reading the rules) the random board generator randomly places any of available object types (stone, pit, reactor, wall, etc.) at any given X/Y coordinate.

I wonder how it ensures, that paths are usable by a robot (e.g. no square 3x3 is generated and in the middle a robot is auto-placed)?

**Comment by shaos** [comment]
It's easy - stones could be destroyed by robot's gun :)

**Comment by aik099** [comment]
Ha-ha. Consume all the ammo just to get out of the cage and drop into nearest pit.

**Comment by shaos** [comment]
don't forget boxes with ammo that located everywhere
